# Generated by Django 6.0 on 2026-02-15 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hh', '0011_sim_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sim',
            name='slug',
        ),
    ]
